name: markymark
description: A simple web server to preview your Markdown files.
version: 0.1.1
environment:
  sdk: ">=2.0.0 <3.0.0"
authors:
- munificent
- thosakwe
dependencies:
  args: ^1.0.0
  markdown: ^2.0.0
  path: ^1.0.0
  shelf: ^0.7.5
  shelf_static: ^0.2.8
  shelf_web_socket: ^0.2.3
dev_dependencies:
  pedantic: ^1.0.0
executables:
  markymark:
